base_conversion: convert.o base_conversion.o
	g++ convert.o base_conversion.o -o base_conversion

convert.o: convert.cpp
	g++ -c convert.cpp

base_conversion.o: base_conversion.cpp
	g++ -c base_conversion.cpp